server:
  port: 8888
  servlet:
    contextPath: /api/v1
# Hibernate ddl auto (create, create-drop, validate, update)
spring:
  application:
    name: usermanagement-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/usermanagement_service
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
    